/*
 Copyright (c) 2007 Bill Six
 
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
 
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
 
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 */
package com.billsix.examples.atm.richclient;

import com.billsix.examples.atm.domain.Account;
import com.billsix.examples.atm.domain.AccountTransaction;
import com.billsix.examples.atm.service.ATMService;
import com.billsix.examples.atm.service.ClientSideServiceLocator;
import com.billsix.examples.atm.service.ClientSideServiceLocatorImplementation;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 * Swing GUI for the ATM.
 *
 *
 * @author Bill Six
 */
public class ATMRichClient extends javax.swing.JFrame {
    
    /** Creates new form ATM */
    public ATMRichClient(ClientSideServiceLocator clientServiceLocator) {
        _atmService = clientServiceLocator.getAtmService();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        _loginDialog = _loginDialog = new javax.swing.JDialog(_atmRichClient);

        loginTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        passwordTextField = new javax.swing.JPasswordField();
        _desktopPane = new javax.swing.JDesktopPane();
        _atmInternalFrame = new javax.swing.JInternalFrame();
        _tabbedPane = new javax.swing.JTabbedPane();
        _currentBalancePanel = new javax.swing.JPanel();
        _currentBalanceLabel = new javax.swing.JLabel();
        _withdrawPanel = new javax.swing.JPanel();
        _amountToWithdrawTextField = new javax.swing.JTextField();
        _amountToWithdrawLabel = new javax.swing.JLabel();
        _amountToWithdrawButton = new javax.swing.JButton();
        _depositPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        _amountToDepositTextField = new javax.swing.JTextField();
        _amountToDepositLabel = new javax.swing.JLabel();
        _amountToDepositButton = new javax.swing.JButton();
        _accountHistoryPanel = new javax.swing.JPanel();
        _scrollPane = new javax.swing.JScrollPane();
        _transactionHistoryTable = new javax.swing.JTable();
        _menuBar = new javax.swing.JMenuBar();
        _menu = new javax.swing.JMenu();
        _fileMenuItem = new javax.swing.JMenuItem();
        _exitMenuItem = new javax.swing.JMenuItem();

        _loginDialog.setTitle("Login");
        _loginDialog.setModal(true);

        jLabel5.setText("Username:");

        jLabel6.setText("Password:");

        jButton3.setText("Login");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginDialogClicked(evt);
            }
        });

        javax.swing.GroupLayout _loginDialogLayout = new javax.swing.GroupLayout(_loginDialog.getContentPane());
        _loginDialog.getContentPane().setLayout(_loginDialogLayout);
        _loginDialogLayout.setHorizontalGroup(
            _loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_loginDialogLayout.createSequentialGroup()
                .addGroup(_loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_loginDialogLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(_loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(47, 47, 47)
                        .addGroup(_loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordTextField, 0, 0, Short.MAX_VALUE)
                            .addComponent(loginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                    .addGroup(_loginDialogLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton3)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        _loginDialogLayout.setVerticalGroup(
            _loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_loginDialogLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(_loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(_loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        _atmInternalFrame.setIconifiable(true);
        _atmInternalFrame.setMaximizable(true);
        _atmInternalFrame.setResizable(true);
        _atmInternalFrame.setTitle("ATM");
        _tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                _tabbedPaneStateChanged(evt);
            }
        });

        _currentBalanceLabel.setText("$");

        javax.swing.GroupLayout _currentBalancePanelLayout = new javax.swing.GroupLayout(_currentBalancePanel);
        _currentBalancePanel.setLayout(_currentBalancePanelLayout);
        _currentBalancePanelLayout.setHorizontalGroup(
            _currentBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_currentBalancePanelLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(_currentBalanceLabel)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        _currentBalancePanelLayout.setVerticalGroup(
            _currentBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_currentBalancePanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(_currentBalanceLabel)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        _tabbedPane.addTab("Current Balance", _currentBalancePanel);

        _amountToWithdrawLabel.setText("Amount To Withdraw");

        _amountToWithdrawButton.setText("Submit");
        _amountToWithdrawButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _amountToWithdrawButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout _withdrawPanelLayout = new javax.swing.GroupLayout(_withdrawPanel);
        _withdrawPanel.setLayout(_withdrawPanelLayout);
        _withdrawPanelLayout.setHorizontalGroup(
            _withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_withdrawPanelLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(_withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_withdrawPanelLayout.createSequentialGroup()
                        .addComponent(_amountToWithdrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_amountToWithdrawButton))
                    .addComponent(_amountToWithdrawLabel))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        _withdrawPanelLayout.setVerticalGroup(
            _withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_withdrawPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(_amountToWithdrawLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_amountToWithdrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_amountToWithdrawButton))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        _tabbedPane.addTab("Withdraw", _withdrawPanel);

        _amountToDepositLabel.setText("Amount To Deposit");

        _amountToDepositButton.setText("Submit");
        _amountToDepositButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                _amountToDepositButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(_amountToDepositTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_amountToDepositButton))
                    .addComponent(_amountToDepositLabel))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(_amountToDepositLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_amountToDepositTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_amountToDepositButton))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout _depositPanelLayout = new javax.swing.GroupLayout(_depositPanel);
        _depositPanel.setLayout(_depositPanelLayout);
        _depositPanelLayout.setHorizontalGroup(
            _depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        _depositPanelLayout.setVerticalGroup(
            _depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        _tabbedPane.addTab("Deposit", _depositPanel);

        _transactionHistoryTable.setModel(getTableModel());
        _scrollPane.setViewportView(_transactionHistoryTable);

        javax.swing.GroupLayout _accountHistoryPanelLayout = new javax.swing.GroupLayout(_accountHistoryPanel);
        _accountHistoryPanel.setLayout(_accountHistoryPanelLayout);
        _accountHistoryPanelLayout.setHorizontalGroup(
            _accountHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        _accountHistoryPanelLayout.setVerticalGroup(
            _accountHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_accountHistoryPanelLayout.createSequentialGroup()
                .addComponent(_scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );
        _tabbedPane.addTab("Account History", _accountHistoryPanel);

        _tabbedPane.getAccessibleContext().setAccessibleName("Withdraw");

        javax.swing.GroupLayout _atmInternalFrameLayout = new javax.swing.GroupLayout(_atmInternalFrame.getContentPane());
        _atmInternalFrame.getContentPane().setLayout(_atmInternalFrameLayout);
        _atmInternalFrameLayout.setHorizontalGroup(
            _atmInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        _atmInternalFrameLayout.setVerticalGroup(
            _atmInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        _atmInternalFrame.setBounds(100, 50, 690, 420);
        _desktopPane.add(_atmInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        _menu.setText("File");
        _fileMenuItem.setText("Log in");
        _fileMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginMenuItemPressed(evt);
            }
        });

        _menu.add(_fileMenuItem);

        _exitMenuItem.setText("Quit");
        _exitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                quitMenuItemPressed(evt);
            }
        });

        _menu.add(_exitMenuItem);

        _menuBar.add(_menu);

        setJMenuBar(_menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void _amountToWithdrawButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__amountToWithdrawButtonMousePressed
        try{
            Double amountToWithdraw = Double.parseDouble(_amountToWithdrawTextField.getText());
            _atmService.withDraw(amountToWithdraw);
            _tabbedPane.setSelectedIndex(0);
            
        } catch(NumberFormatException nfe) {
            JOptionPane.showMessageDialog(_atmRichClient, "Please enter a decimal") ;
        }
    }//GEN-LAST:event__amountToWithdrawButtonMousePressed
    
    private void _amountToDepositButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__amountToDepositButtonMousePressed
        try{
            Double amountToDeposit = Double.parseDouble(_amountToDepositTextField.getText());
            _atmService.deposit(amountToDeposit);
            _tabbedPane.setSelectedIndex(0);
        } catch(NumberFormatException nfe) {
            JOptionPane.showMessageDialog(_atmRichClient, "Please enter a decimal") ;
        }
    }//GEN-LAST:event__amountToDepositButtonMousePressed
    
    private void _tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event__tabbedPaneStateChanged
        if(_atmInternalFrame.isVisible()) {
            JTabbedPane tabbedPane = (JTabbedPane) evt.getSource();
            if(tabbedPane.getSelectedIndex() == 0) {
                refreshCurrentBalanceFigure();
            }
            if(tabbedPane.getSelectedIndex() == 3) {
                refreshAccountHistoryTable();
            }
        }
    }//GEN-LAST:event__tabbedPaneStateChanged
    
    private void refreshCurrentBalanceFigure() {
        Double currentBalance = _atmService.getBalance();
        _currentBalanceLabel.setText("$" + currentBalance.toString());
    }
    
    private void refreshAccountHistoryTable() {
        Account account =  _atmService.fetchAccountTransactions();
        while(_tableModel.getRowCount() > 0) {
            _tableModel.removeRow(0);
        }
        for(AccountTransaction transaction : account.getTransactionHistory()) {
            String id = transaction.getAccount().getId().toString();
            _tableModel.addRow(new Object[]{id, _dateFormat.format(transaction.getDate().getTime()),transaction.getBalanceBeforeTransaction(), transaction.getBalanceAfterTransaction()});
        }
        _transactionHistoryTable.repaint();
    }
    
    
    private void quitMenuItemPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitMenuItemPressed
        System.exit(0);
    }//GEN-LAST:event_quitMenuItemPressed
    
    private void loginMenuItemPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMenuItemPressed
        _loginDialog.pack();
        _loginDialog.setLocationRelativeTo(_atmRichClient);
        _loginDialog.setVisible(true);
    }//GEN-LAST:event_loginMenuItemPressed
    
    private void loginDialogClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginDialogClicked
        String username = loginTextField.getText();
        String password = passwordTextField.getText();
        if(_atmService.authenticate(username, password)) {
            _loginDialog.setVisible(false);
            _atmInternalFrame.setVisible(true);
            refreshCurrentBalanceFigure();
        } else {
            System.out.println("failed to log in");
        }
    }//GEN-LAST:event_loginDialogClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                _atmRichClient = new ATMRichClient(ClientSideServiceLocatorImplementation.getInstance());
                _atmRichClient.setVisible(true);
            }
        });
        
    }    
    
    public TableModel getTableModel() {
        return _tableModel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _accountHistoryPanel;
    private javax.swing.JButton _amountToDepositButton;
    private javax.swing.JLabel _amountToDepositLabel;
    private javax.swing.JTextField _amountToDepositTextField;
    private javax.swing.JButton _amountToWithdrawButton;
    private javax.swing.JLabel _amountToWithdrawLabel;
    private javax.swing.JTextField _amountToWithdrawTextField;
    private javax.swing.JInternalFrame _atmInternalFrame;
    private javax.swing.JLabel _currentBalanceLabel;
    private javax.swing.JPanel _currentBalancePanel;
    private javax.swing.JPanel _depositPanel;
    private javax.swing.JDesktopPane _desktopPane;
    private javax.swing.JMenuItem _exitMenuItem;
    private javax.swing.JMenuItem _fileMenuItem;
    private javax.swing.JDialog _loginDialog;
    private javax.swing.JMenu _menu;
    private javax.swing.JMenuBar _menuBar;
    private javax.swing.JScrollPane _scrollPane;
    private javax.swing.JTabbedPane _tabbedPane;
    private javax.swing.JTable _transactionHistoryTable;
    private javax.swing.JPanel _withdrawPanel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JPasswordField passwordTextField;
    // End of variables declaration//GEN-END:variables
    
    private javax.swing.table.DefaultTableModel _tableModel = new DefaultTableModel(new String[]{"Account Number","Transaction Date","Balance Before Transaction","Balance After Transaction"}, 0);
    private DateFormat _dateFormat = new SimpleDateFormat("EEE, d MMM yyyy HH:mm:ss Z");
    private static ATMRichClient _atmRichClient;
    private static ATMService _atmService;    
}
